condition.plugin.embargo_embargoed_condition:
  type: condition.plugin
  mapping:
    filter:
      type: text
      label: 'Node is embargoed'

embargo.settings:
  type: config_object
  mapping:
    contact_email:
      type: email
      label: 'Contact email for embargo notifications'
    notification_message:
      type: text
      label: 'Embargo notification message'
