---
name: PHPUnit Tests
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  PHPUnit:
    uses: discoverygarden/phpunit-action/.github/workflows/phpunit.yml@v1
    secrets: inherit
    with:
      composer.rereqs: >-
        "discoverygarden/islandora_test_support:^1"
